name: Yatirim Botu Calistir
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with: {python-version: '3.10'}
      - name: Kutuphaneleri Yukle
        run: pip install pyTelegramBotAPI yfinance pandas matplotlib feedparser textblob google-generativeai
      - name: Botu Baslat
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
